### ISSUE TITLE
altera_fit.tcl does not start when project is cached.

### ISSUE THREAD

**Issue by hanw** [hanw/sonic-lite#3]
process stuck after altera_map.tcl is completed if the project was compiled and cached before.

**Comment by hanw** [comment]
^CUnexpected error: (<type 'exceptions.KeyboardInterrupt'>, KeyboardInterrupt(), <traceback object at 0x161fb00>)
Traceback (most recent call last):
  File "/home/hwang/dev/buildcache/buildcache", line 310, in <module>
    check_md5sum()
  File "/home/hwang/dev/buildcache/buildcache", line 233, in check_md5sum
    p.wait()
  File "/usr/lib/python2.7/subprocess.py", line 1291, in wait
    pid, sts = _eintr_retry_call(os.waitpid, self.pid, 0)
  File "/usr/lib/python2.7/subprocess.py", line 478, in _eintr_retry_call
    return func(*args)
KeyboardInterrupt

**Comment by hanw** [comment]
fixed by skip caching for quartus_sh
